title:             Justice Free Website Template, Free HTML5 Template by gettemplates.co
email:             your-email@example.com
description:
author:

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-coffeescript

exclude:
  - LICENSE
  - README.md
  - justice.gif

# Social Profiles
twitter_username: ""
github_username: ""
facebook_username: ""
